# Form implementation generated from reading ui file 'Items.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Items(object):
    def setupUi(self, Items):
        Items.setObjectName("Items")
        Items.resize(534, 113)
        self.textEdit = QtWidgets.QTextEdit(parent=Items)
        self.textEdit.setGeometry(QtCore.QRect(30, 50, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.textEdit.setReadOnly(False)
        self.textEdit.setObjectName("textEdit")
        self.spinWeight = QtWidgets.QSpinBox(parent=Items)
        self.spinWeight.setGeometry(QtCore.QRect(250, 50, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.spinWeight.setFont(font)
        self.spinWeight.setReadOnly(False)
        self.spinWeight.setObjectName("spinWeight")
        self.spinValue = QtWidgets.QSpinBox(parent=Items)
        self.spinValue.setGeometry(QtCore.QRect(370, 50, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.spinValue.setFont(font)
        self.spinValue.setReadOnly(False)
        self.spinValue.setObjectName("spinValue")
        self.label = QtWidgets.QLabel(parent=Items)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-weight: bold;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Items)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Items)
        self.label_3.setGeometry(QtCore.QRect(370, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-weight: bold;")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Items)
        QtCore.QMetaObject.connectSlotsByName(Items)

    def retranslateUi(self, Items):
        _translate = QtCore.QCoreApplication.translate
        Items.setWindowTitle(_translate("Items", "Form"))
        self.label.setText(_translate("Items", "Item Name"))
        self.label_2.setText(_translate("Items", "Weight"))
        self.label_3.setText(_translate("Items", "Value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Items = QtWidgets.QWidget()
    ui = Ui_Items()
    ui.setupUi(Items)
    Items.show()
    sys.exit(app.exec())
