# Form implementation generated from reading ui file 'NotFound.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NotFound(object):
    def setupUi(self, NotFound):
        NotFound.setObjectName("NotFound")
        NotFound.resize(523, 284)
        self.label = QtWidgets.QLabel(parent=NotFound)
        self.label.setGeometry(QtCore.QRect(130, 60, 261, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(NotFound)
        QtCore.QMetaObject.connectSlotsByName(NotFound)

    def retranslateUi(self, NotFound):
        _translate = QtCore.QCoreApplication.translate
        NotFound.setWindowTitle(_translate("NotFound", "Form"))
        self.label.setText(_translate("NotFound", "There are no results matching your request\nPlease Try again!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NotFound = QtWidgets.QWidget()
    ui = Ui_NotFound()
    ui.setupUi(NotFound)
    NotFound.show()
    sys.exit(app.exec())
